/* eslint-disable */

const { open, readdir, access, mkdir, writeFile, appendFile, rm } = require('node:fs/promises');
const path = require('node:path');

const { parseXml } = require('@rgrove/parse-xml');
const camelCase = require('lodash/camelCase');
const template = require('lodash/template');

const iconsPath = path.resolve(__dirname, '../components/icons');

const generateDir = async (currentPath) => {
  try {
    await mkdir(currentPath, { recursive: true });
  } catch (err) {
    console.error(err.message);
  }
};

/**
 * Process SVG structure to extract elements compatible with react-native-svg
 * Returns an array of SVG element definitions
 */
const processSvgStructure = (svgStructure, replaceFillOrStrokeColor) => {
  const elements = [];

  if (!svgStructure?.children?.length) return elements;

  // Filter out text and defs elements (defs not supported in react-native-svg)
  svgStructure.children = svgStructure.children.filter(
    (c) => c.type !== 'text' && c.name !== 'defs'
  );

  for (const child of svgStructure.children) {
    if (child.type !== 'element') continue;

    const attrs = child.attributes || {};
    const processed = { type: child.name, props: {} };

    // Handle fill - for vendor icons, always use currentColor; for public, only 'none' becomes currentColor
    if (attrs.fill) {
      if (replaceFillOrStrokeColor) {
        processed.props.fill = 'currentColor';
      } else if (attrs.fill === 'none') {
        processed.props.fill = 'currentColor';
      } else {
        processed.props.fill = attrs.fill;
      }
    }

    // Handle stroke - for vendor icons, always use currentColor
    if (attrs.stroke) {
      processed.props.stroke = replaceFillOrStrokeColor ? 'currentColor' : attrs.stroke;
    }

    // Copy relevant attributes
    const scalarProps = [
      'strokeWidth',
      'strokeLinecap',
      'strokeLinejoin',
      'strokeDasharray',
      'opacity',
      'clipPath',
      'transform',
      'd',
      'rx',
      'ry',
      'cx',
      'cy',
      'r',
      'x',
      'y',
      'width',
      'height',
      'x1',
      'x2',
      'y1',
      'y2',
      'points',
    ];

    for (const prop of scalarProps) {
      if (attrs[prop] !== undefined) {
        processed.props[prop] = attrs[prop];
      }
    }

    // Handle children recursively
    if (child.children?.length) {
      processed.children = processSvgStructure(child, replaceFillOrStrokeColor);
    }

    elements.push(processed);
  }

  return elements;
};

/**
 * Extract viewBox and size from SVG root element
 */
const extractSvgMetadata = (svgStructure) => {
  const attrs = svgStructure.attributes || {};
  return {
    viewBox: attrs.viewBox || `0 0 ${attrs.width || 24} ${attrs.height || 24}`,
    width: attrs.width || 24,
    height: attrs.height || 24,
  };
};

/**
 * Generate React Native SVG component that renders from JSON data
 */
const generateSvgComponent = async (fileHandle, entry, pathList, replaceFillOrStrokeColor) => {
  const currentPath = path.resolve(iconsPath, 'src', ...pathList.slice(2));

  try {
    await access(currentPath);
  } catch {
    await generateDir(currentPath);
  }

  const svgString = await fileHandle.readFile({ encoding: 'utf8' });
  const svgJson = parseXml(svgString).toJSON();
  const svgStructure = svgJson.children[0];
  const elements = processSvgStructure(svgStructure, replaceFillOrStrokeColor);
  const metadata = extractSvgMetadata(svgStructure);

  const prefixFileName = camelCase(entry.split('.')[0]);
  const fileName = prefixFileName.charAt(0).toUpperCase() + prefixFileName.slice(1);

  // Generate SVG data JSON
  const svgData = {
    name: fileName,
    viewBox: metadata.viewBox,
    elements,
  };

  // Generate component that uses IconBase wrapped in Pressable for onPress support
  const componentRender = template(
    `
// GENERATED BY script
// DO NOT EDIT IT MANUALLY

import * as React from 'react';
import { Pressable } from 'react-native';

import IconBase from '@/components/icons/IconBase';
import type { IconBaseProps, IconData } from '@/components/icons/types';

import data from './<%= svgName %>.json';

const <%= svgName %> = React.forwardRef<React.ElementRef<typeof Pressable>, IconBaseProps>(
  ({ onPress, ...props }, ref) => (
    <Pressable onPress={onPress} ref={ref}>
      <IconBase {...props} data={data as IconData} />
    </Pressable>
  )
);

<%= svgName %>.displayName = '<%= svgName %>';

export default <%= svgName %>;
`.trim()
  );

  // Write JSON data file
  await writeFile(path.resolve(currentPath, `${fileName}.json`), JSON.stringify(svgData, '', '\t'));

  // Write component file
  await writeFile(
    path.resolve(currentPath, `${fileName}.tsx`),
    `${componentRender({ svgName: fileName })}\n`
  );

  // Append to index
  const indexingRender = template(
    `
export { default as <%= svgName %> } from './<%= svgName %>';
`.trim()
  );

  await appendFile(
    path.resolve(currentPath, 'index.ts'),
    `${indexingRender({ svgName: fileName })}\n`
  );
};

/**
 * Generate image component for PNG assets
 */
const generateImageComponent = async (entry, pathList) => {
  const currentPath = path.resolve(iconsPath, 'src', ...pathList.slice(2));

  try {
    await access(currentPath);
  } catch {
    await generateDir(currentPath);
  }

  const prefixFileName = camelCase(entry.split('.')[0]);
  const fileName = prefixFileName.charAt(0).toUpperCase() + prefixFileName.slice(1);

  // Calculate the relative path from the component file to the asset
  // The component is at: components/icons/src/image/common/Layer.tsx
  // The asset is at: components/icons/assets/image/common/layer.png
  // From src/image/common/ we need ../../ to reach components/icons/
  const assetRelativePath = path.join(...pathList.slice(2), entry).replace(/\\/g, '/');
  const depth = pathList.slice(2).length; // e.g., ['image', 'common'] = 2 levels
  // Go up 'depth' levels to reach icons/ (where src/ and assets/ are siblings)
  const relativePath = '../'.repeat(depth) + `assets/${assetRelativePath}`;

  // For React Native, wrap Image with Pressable to support onPress
  const componentRender = template(
    `
// GENERATED BY script
// DO NOT EDIT IT MANUALLY

import * as React from 'react';
import { Image, Pressable } from 'react-native';

import type { ImageIconBaseProps } from '@/components/icons/types';

const <%= fileName %> = React.forwardRef<React.ElementRef<typeof Pressable>, ImageIconBaseProps>(
  ({ size = 20, onPress, ...restProps }, ref) => (
    <Pressable onPress={onPress} {...restProps} ref={ref}>
      <Image
        source={<%= assetPath %>}
        style={{ width: size, height: size }}
      />
    </Pressable>
  )
);

<%= fileName %>.displayName = '<%= fileName %>';

export default <%= fileName %>;
`.trim()
  );

  // Use require() with a static path - React Native requires static requires
  await writeFile(
    path.resolve(currentPath, `${fileName}.tsx`),
    `${componentRender({
      fileName,
      assetPath: `require("${relativePath}")`,
    })}\n`
  );

  const indexingRender = template(
    `
export { default as <%= fileName %> } from './<%= fileName %>';
`.trim()
  );

  await appendFile(path.resolve(currentPath, 'index.ts'), `${indexingRender({ fileName })}\n`);
};

const walk = async (entry, pathList, replaceFillOrStrokeColor) => {
  const currentPath = path.resolve(...pathList, entry);
  let fileHandle;

  try {
    fileHandle = await open(currentPath);
    const stat = await fileHandle.stat();

    if (stat.isDirectory()) {
      const files = await readdir(currentPath);

      for (const file of files) await walk(file, [...pathList, entry], replaceFillOrStrokeColor);
    }

    if (stat.isFile() && /.+\.svg$/g.test(entry))
      await generateSvgComponent(fileHandle, entry, pathList, replaceFillOrStrokeColor);

    if (stat.isFile() && /.+\.png$/g.test(entry)) await generateImageComponent(entry, pathList);
  } finally {
    fileHandle?.close();
  }
};

(async () => {
  await rm(path.resolve(iconsPath, 'src'), {
    recursive: true,
    force: true,
  });

  // +++ Pre-create directories +++
  await generateDir(path.resolve(iconsPath, 'assets/public'));
  await generateDir(path.resolve(iconsPath, 'assets/vendor'));
  await generateDir(path.resolve(iconsPath, 'assets/image'));

  await walk('public', [iconsPath, 'assets']);
  await walk('vendor', [iconsPath, 'assets'], true);
  await walk('image', [iconsPath, 'assets']);

  console.log('Icon generation complete!');
})();
