// GENERATED BY script
// DO NOT EDIT IT MANUALLY

import * as React from 'react';
import { Image, Pressable } from 'react-native';

import type { ImageIconBaseProps } from '@/components/icons/types';

const Layer = React.forwardRef<React.ElementRef<typeof Pressable>, ImageIconBaseProps>(
  ({ size = 20, onPress, ...restProps }, ref) => (
    <Pressable onPress={onPress} {...restProps} ref={ref}>
      <Image
        source={require("../../assets/image/common/layer.png")}
        style={{ width: size, height: size }}
      />
    </Pressable>
  )
);

Layer.displayName = 'Layer';

export default Layer;
