import type { Hotel } from '@/src/store/hotel';

export const defaultRecentSearches: Hotel[] = [
  { name: 'Cordis, Hong Kong' },
  { name: 'The Langham, Hong Kong' },
];

export interface PopularHotel {
  name: string;
  location: string;
}

// TODO: Mock data for popular hotels in Hong Kong. In a real app, this would come from an API or database.
export const POPULAR_HOTELS: PopularHotel[] = [
  // ===== Luxury / 5-star =====
  { name: 'The Peninsula Hong Kong', location: 'Tsim Sha Tsui' },
  { name: 'Mandarin Oriental, Hong Kong', location: 'Central' },
  { name: 'The Langham, Hong Kong', location: 'Tsim Sha Tsui' },
  { name: 'The St. Regis Hong Kong', location: 'Wan Chai' },
  { name: 'The Murray, Hong Kong', location: 'Central' },
  { name: 'The Silveri Hong Kong - MGallery', location: 'Tung Chung' },
  { name: 'Island Shangri-La, Hong Kong', location: 'Admiralty' },
  { name: 'Kowloon Shangri-La, Hong Kong', location: 'Tsim Sha Tsui East' },
  { name: 'The Ritz-Carlton, Hong Kong', location: 'West Kowloon' },
  { name: 'Rosewood Hong Kong', location: 'Tsim Sha Tsui' },
  { name: 'Four Seasons Hotel Hong Kong', location: 'Central' },
  { name: 'Grand Hyatt Hong Kong', location: 'Wan Chai' },
  { name: 'Conrad Hong Kong', location: 'Admiralty' },
  { name: 'JW Marriott Hotel Hong Kong', location: 'Admiralty' },
  { name: 'The Upper House', location: 'Admiralty' },
  { name: 'Cordis, Hong Kong', location: 'Mong Kok' },
  { name: 'W Hong Kong', location: 'West Kowloon' },
  { name: 'Hotel ICON', location: 'Tsim Sha Tsui East' },
  { name: 'InterContinental Grand Stanford Hong Kong', location: 'Tsim Sha Tsui East' },
  { name: 'Regent Hong Kong', location: 'Tsim Sha Tsui' },
  { name: 'Hyatt Regency Hong Kong, Tsim Sha Tsui', location: 'Tsim Sha Tsui' },
  { name: 'Hyatt Regency Hong Kong, Sha Tin', location: 'Sha Tin' },
  { name: 'The Kowloon Hotel', location: 'Tsim Sha Tsui' },
  { name: 'The Mira Hong Kong', location: 'Tsim Sha Tsui' },
  { name: 'Marco Polo Hongkong Hotel', location: 'Tsim Sha Tsui' },
  { name: 'Gateway Hotel, Marco Polo', location: 'Tsim Sha Tsui' },
  { name: 'Prince Hotel, Marco Polo', location: 'Tsim Sha Tsui' },
  { name: 'New World Millennium Hong Kong Hotel', location: 'Tsim Sha Tsui East' },
  { name: 'Sheraton Hong Kong Hotel & Towers', location: 'Tsim Sha Tsui' },
  { name: 'Sheraton Hong Kong Tung Chung Hotel', location: 'Tung Chung' },
  { name: 'Hotel Nikko Hong Kong', location: 'Tsim Sha Tsui East' },
  { name: 'Royal Garden Hotel', location: 'Tsim Sha Tsui East' },
  { name: 'Royal Plaza Hotel', location: 'Mong Kok' },
  { name: 'Eaton HK', location: 'Jordan' },
  { name: 'Harbour Grand Kowloon', location: 'Hung Hom' },
  { name: 'Harbour Grand Hong Kong', location: 'North Point' },
  { name: 'Harbour Plaza North Point', location: 'North Point' },
  { name: 'Harbour Plaza 8 Degrees', location: 'To Kwa Wan' },
  { name: 'Harbour Plaza Resort City', location: 'Tin Shui Wai' },
  { name: 'Crowne Plaza Hong Kong Causeway Bay', location: 'Causeway Bay' },
  { name: 'Crowne Plaza Hong Kong Kowloon East', location: 'Tseung Kwan O' },
  { name: 'Holiday Inn Express Causeway Bay Hong Kong', location: 'Causeway Bay' },
  { name: 'Holiday Inn Express Hong Kong Kowloon East', location: 'Tseung Kwan O' },
  { name: 'Holiday Inn Express Hong Kong Mongkok', location: 'Mong Kok' },
  { name: 'Holiday Inn Express Hong Kong Soho', location: 'Sheung Wan' },
  { name: 'Holiday Inn Golden Mile Hong Kong', location: 'Tsim Sha Tsui' },
  { name: 'InterContinental Hong Kong', location: 'Tsim Sha Tsui' },
  { name: 'Cordis Mongkok', location: 'Mong Kok' },
  { name: 'Pentahotel Hong Kong, Kowloon', location: 'Diamond Hill' },
  { name: 'Hotel Indigo Hong Kong Island', location: 'Wan Chai' },
  { name: 'Dorsett Wanchai, Hong Kong', location: 'Wan Chai' },
  { name: 'Dorsett Mongkok, Hong Kong', location: 'Mong Kok' },
  { name: 'Dorsett Tsuen Wan, Hong Kong', location: 'Tsuen Wan' },
  { name: 'Dorsett Kwun Tong, Hong Kong', location: 'Kwun Tong' },
  { name: 'Silka Seaview Hotel Hong Kong', location: 'Yau Ma Tei' },
  { name: 'Silka West Kowloon Hotel', location: 'Tai Kok Tsui' },
  { name: 'Silka Far East Hotel', location: 'Tsuen Wan' },
  { name: 'Silka Tsuen Wan Hong Kong', location: 'Tsuen Wan' },
  { name: 'L’hotel Causeway Bay Harbour View', location: 'Causeway Bay' },
  { name: 'L’hotel Island South', location: 'Wong Chuk Hang' },
  { name: 'L’hotel élan', location: 'Kwun Tong' },
  { name: 'Park Hotel Hong Kong', location: 'Tsim Sha Tsui East' },
  { name: 'Empire Hotel Kowloon - Tsim Sha Tsui', location: 'Tsim Sha Tsui' },
  { name: 'Empire Hotel Hong Kong - Causeway Bay', location: 'Causeway Bay' },
  { name: 'Empire Hotel Hong Kong - Wan Chai', location: 'Wan Chai' },
  { name: 'Mira Moon Hotel', location: 'Causeway Bay' },
  { name: 'Mini Hotel Central', location: 'Sheung Wan' },
  { name: 'Mini Hotel Causeway Bay', location: 'Causeway Bay' },
  { name: 'Tuve', location: 'Tin Hau' },
  { name: 'Hotel Stage', location: 'Jordan' },
  { name: 'The Pottinger Hong Kong', location: 'Central' },
  { name: 'The Fleming', location: 'Wan Chai' },
  { name: 'The Hari Hong Kong', location: 'Wan Chai' },
  { name: 'The Park Lane Hong Kong, a Pullman Hotel', location: 'Causeway Bay' },
  { name: 'Pullman Hong Kong Kai Tak', location: 'Kai Tak' },
  { name: 'Novotel Citygate Hong Kong', location: 'Tung Chung' },
  { name: 'Novotel Century Hong Kong', location: 'Wan Chai' },
  { name: 'Novotel Nathan Road Kowloon Hong Kong', location: 'Yau Ma Tei' },
  { name: 'ibis Hong Kong Central and Sheung Wan', location: 'Sheung Wan' },
  { name: 'ibis Hong Kong North Point', location: 'North Point' },
  { name: 'Hotel Pravo', location: 'Jordan' },
  { name: 'Madera Hong Kong', location: 'Jordan' },
  { name: 'Madera Hollywood', location: 'Sheung Wan' },
  { name: 'The Mercer', location: 'Sheung Wan' },
  { name: 'The Wharney Guang Dong Hotel Hong Kong', location: 'Wan Chai' },
  { name: 'The Charterhouse Causeway Bay', location: 'Causeway Bay' },
  { name: 'Bishop Lei International House', location: 'Mid-Levels' },
  { name: 'Garden View Hong Kong', location: 'Mid-Levels' },
  { name: 'iclub Sheung Wan Hotel', location: 'Sheung Wan' },
  { name: 'iclub Wan Chai Hotel', location: 'Wan Chai' },
  { name: 'iclub Fortress Hill Hotel', location: 'Fortress Hill' },
  { name: 'iclub Mong Kok Hotel', location: 'Mong Kok' },
  { name: 'iclub To Kwa Wan Hotel', location: 'To Kwa Wan' },
  { name: 'iclub Ma Tau Wai Hotel', location: 'Ma Tau Wai' },
  { name: 'Best Western Hotel Causeway Bay', location: 'Causeway Bay' },
  { name: 'Best Western Plus Hotel Hong Kong', location: 'Sai Ying Pun' },
  { name: 'Best Western Grand Hotel', location: 'Tsim Sha Tsui' },
  { name: 'The Salisbury - YMCA of Hong Kong', location: 'Tsim Sha Tsui' },
  { name: 'BP International', location: 'Jordan' },
  { name: 'YHA Mei Ho House Youth Hostel', location: 'Sham Shui Po' },
  { name: 'Caritas Bianchi Lodge', location: 'Yau Ma Tei' },
  { name: 'Pentahotel Hong Kong Tuen Mun', location: 'Tuen Mun' },

  // ===== Mid-range & boutique =====
  { name: 'South Pacific Hotel', location: 'Wan Chai' },
  { name: 'The Cityview', location: 'Yau Ma Tei' },
  { name: 'Stanford Hillview Hotel', location: 'Tsim Sha Tsui' },
  { name: 'Stanford Hotel', location: 'Mong Kok' },
  { name: 'Casa Hotel', location: 'Sheung Wan' },
  { name: 'Hotel LBP', location: 'Sai Ying Pun' },
  { name: 'Butterfly on Morrison Boutique Hotel', location: 'Causeway Bay' },
  { name: 'Butterfly on Wellington Boutique Hotel', location: 'Central' },
  { name: 'Butterfly on Hollywood Boutique Hotel', location: 'Sheung Wan' },
  { name: 'Butterfly on Prat Boutique Hotel', location: 'Tsim Sha Tsui' },
  { name: 'Butterfly on Waterfront Boutique Hotel', location: 'Sheung Wan' },
  { name: 'Hotel Pennington by Rhombus', location: 'Causeway Bay' },
  { name: 'Hotel Bonaparte by Rhombus', location: 'Wan Chai' },
  { name: 'Hotel sav', location: 'Hung Hom' },
  { name: 'Metropark Hotel Causeway Bay', location: 'Causeway Bay' },
  { name: 'Metropark Hotel Wanchai', location: 'Wan Chai' },
  { name: 'Metropark Hotel Mongkok', location: 'Mong Kok' },
  { name: 'Metropark Hotel Kowloon', location: 'Yau Ma Tei' },
  { name: 'Rambler Garden Hotel', location: 'Tsuen Wan' },
  { name: 'Rambler Oasis Hotel', location: 'Tsuen Wan' },
  { name: 'Royal View Hotel', location: 'Tsuen Wan' },
  { name: 'Panda Hotel', location: 'Tsuen Wan' },
  { name: 'Regal Airport Hotel', location: 'Chek Lap Kok' },
  { name: 'Regal Hongkong Hotel', location: 'Causeway Bay' },
  { name: 'Regal Kowloon Hotel', location: 'Tsim Sha Tsui East' },
  { name: 'Regal Oriental Hotel', location: 'Kowloon City' },
  { name: 'Regal Riverside Hotel', location: 'Sha Tin' },
  { name: 'Hong Kong SkyCity Marriott Hotel', location: 'Chek Lap Kok' },
  { name: 'Novotel Hong Kong Citygate', location: 'Tung Chung' },
  { name: 'Hong Kong Disneyland Hotel', location: 'Lantau Island' },
  { name: 'Disney Explorers Lodge', location: 'Lantau Island' },
  { name: 'Disney’s Hollywood Hotel', location: 'Lantau Island' },
  { name: 'Auberge Discovery Bay Hong Kong', location: 'Discovery Bay' },
  { name: 'The Olympian Hong Kong', location: 'West Kowloon' },
  { name: 'WM Hotel', location: 'Sai Kung' },
  { name: 'The Pier Hotel', location: 'Sheung Wan' },
  { name: 'The Jervois', location: 'Sheung Wan' },
  { name: 'The Bauhinia Hotel - Central', location: 'Central' },
  { name: 'The Bauhinia Hotel - TST', location: 'Tsim Sha Tsui' },
  { name: 'Lan Kwai Fong Hotel @ Kau U Fong', location: 'Sheung Wan' },
  { name: 'The Luxe Manor', location: 'Tsim Sha Tsui' },
  { name: 'Oakwood Studios Hong Kong', location: 'Mid-Levels' },
  { name: 'Bridal Tea House Hotel - Hung Hom Winslow Street', location: 'Hung Hom' },
  { name: 'Bridal Tea House Hotel - Hung Hom Gillies Avenue South', location: 'Hung Hom' },
  { name: 'Bridal Tea House Hotel - Yau Ma Tei', location: 'Yau Ma Tei' },
  { name: 'Bridal Tea House Hotel - Jordan', location: 'Jordan' },
  { name: 'Bridal Tea House Hotel - To Kwa Wan', location: 'To Kwa Wan' },
  { name: 'Bridal Tea House Hotel - Tai Kok Tsui', location: 'Tai Kok Tsui' },
  { name: 'Bridal Tea House Hotel - Anchor Street', location: 'Tai Kok Tsui' },
  { name: 'Bridal Tea House Hotel - Western District', location: 'Sai Ying Pun' },
  { name: 'Wanchai 88 Hotel', location: 'Wan Chai' },
  { name: 'V Wanchai Hotel', location: 'Wan Chai' },
  { name: 'V Wanchai 2 Hotel', location: 'Wan Chai' },
  { name: 'V Causeway Bay', location: 'Causeway Bay' },
  { name: 'Wang Fat Hostel', location: 'Causeway Bay' },
  { name: 'Yesinn @ Causeway Bay', location: 'Causeway Bay' },
  { name: 'Yesinn @ Fortress Hill', location: 'Fortress Hill' },
  { name: 'Check Inn HK', location: 'Mong Kok' },
  { name: 'Mojo Nomad Aberdeen Harbour', location: 'Aberdeen' },
  { name: 'Mojo Nomad Central', location: 'Central' },
  { name: 'Ovolo Central', location: 'Central' },
  { name: 'Ovolo Southside', location: 'Wong Chuk Hang' },
  { name: 'The Park Hotel Hong Kong', location: 'Tsim Sha Tsui East' },
  { name: 'The Aberdeen Marina Club Hotel', location: 'Aberdeen' },
  { name: 'Tai O Heritage Hotel', location: 'Tai O' },
  { name: 'Le Méridien Cyberport', location: 'Pok Fu Lam' },
  { name: 'Tung Wah Hotel', location: 'Sheung Wan' },
  { name: 'YMCA Bridges Street Centre', location: 'Sheung Wan' },
  { name: 'Caritas Lodge - Mong Kok', location: 'Mong Kok' },
  { name: 'Hop Inn on Carnarvon', location: 'Tsim Sha Tsui' },
  { name: 'Hop Inn on Mody', location: 'Tsim Sha Tsui East' },
  { name: 'Hotel Alexandra', location: 'North Point' },
  { name: 'Island Pacific Hotel', location: 'Sai Ying Pun' },
  { name: 'Hotel Jen Hong Kong', location: 'Sai Ying Pun' },
  { name: 'The Henry Hong Kong', location: 'Tsim Sha Tsui East' },
  { name: 'Eaton Residences Wan Chai', location: 'Wan Chai' },
  { name: 'The Royal Pacific Hotel and Towers', location: 'Tsim Sha Tsui' },
  { name: 'Hotel Panorama by Rhombus', location: 'Tsim Sha Tsui' },
  { name: 'Kimberley Hotel', location: 'Tsim Sha Tsui' },
  { name: 'BP International House', location: 'Jordan' },
  { name: 'The Cityview Hotel', location: 'Yau Ma Tei' },
  { name: 'Booth Lodge', location: 'Yau Ma Tei' },
  { name: 'Stanford Tsim Sha Tsui', location: 'Tsim Sha Tsui' },
  { name: 'Sav Hotel', location: 'Hung Hom' },
  { name: 'Pearl Sea Coast Hotel', location: 'Sai Ying Pun' },
  { name: 'CM+ Hotels & Serviced Apartments', location: 'Sai Ying Pun' },
  { name: 'OYO Mongkok Hotel', location: 'Mong Kok' },
  { name: 'M1 Hotel Hung Hom', location: 'Hung Hom' },
  { name: 'M1 Hotel North Point', location: 'North Point' },
  { name: 'M1 Hotel Tsuen Wan', location: 'Tsuen Wan' },
  { name: 'TUVE Hotel', location: 'Tin Hau' },
  { name: 'Camlux Hotel', location: 'Kowloon Bay' },
  { name: 'Mira Place Hotel', location: 'Tsim Sha Tsui' },
  { name: 'The Park Lane Hong Kong', location: 'Causeway Bay' },
  { name: 'AKVO Hotel', location: 'Sai Ying Pun' },
  { name: 'Page Hotel', location: 'Sheung Wan' },
  { name: 'PopInn Hotel', location: 'Mong Kok' },
  { name: 'Citadines Mercer Hong Kong', location: 'Sheung Wan' },
  { name: 'Citadines Harbourview Hong Kong', location: 'Wan Chai' },
  { name: 'Shama Central Hong Kong', location: 'Central' },
  { name: 'Shama Hub Causeway Bay Hong Kong', location: 'Causeway Bay' },
  { name: 'Shama Tsim Sha Tsui', location: 'Tsim Sha Tsui' },
  { name: 'The V Causeway Bay', location: 'Causeway Bay' },
  { name: 'The V Happy Valley', location: 'Happy Valley' },

  // ===== Budget & guesthouses =====
  { name: 'Chungking Mansions Guest House', location: 'Tsim Sha Tsui' },
  { name: 'New Mirador Mansion', location: 'Tsim Sha Tsui' },
  { name: 'Hop Inn on Hankow', location: 'Tsim Sha Tsui' },
  { name: 'Comfort Inn Hong Kong', location: 'Mong Kok' },
  { name: 'Casa Deluxe Hotel', location: 'Mong Kok' },
  { name: 'Hotel sáv', location: 'Hung Hom' },
  { name: 'Sohotel', location: 'Sheung Wan' },
  { name: 'Lan Kwai Fong Hotel @ Kau U Fong (East Wing)', location: 'Sheung Wan' },
  { name: 'Lan Kwai Fong Hotel @ Kau U Fong (West Wing)', location: 'Sheung Wan' },
  { name: 'Hotel Madera Tsim Sha Tsui', location: 'Tsim Sha Tsui' },
  { name: 'Hotel Madera Wan Chai', location: 'Wan Chai' },
  { name: 'Hotel TRYP by Wyndham', location: 'Sai Ying Pun' },
  { name: 'Wyndham Garden Wan Chai', location: 'Wan Chai' },
  { name: 'Ramada Hong Kong Grand', location: 'North Point' },
  { name: 'Ramada Hong Kong Harbour View', location: 'Sai Wan Ho' },
  { name: 'Travelodge Central, Hollywood Road', location: 'Central' },
  { name: 'Travelodge Central, Lan Kwai Fong', location: 'Central' },
  { name: 'Travelodge Hong Kong Cityview', location: 'Mong Kok' },
  { name: 'Travelodge Kowloon', location: 'Tsim Sha Tsui' },
  { name: 'Travelodge Kowloon Pearl', location: 'Hung Hom' },
  { name: 'Travelodge Sai Ying Pun', location: 'Sai Ying Pun' },
  { name: 'TST Cosy Hotel', location: 'Tsim Sha Tsui' },
  { name: 'Class Hotel', location: 'Mong Kok' },
  { name: 'Casa Hotel TST', location: 'Tsim Sha Tsui' },
  { name: 'Apple Hotel', location: 'Mong Kok' },
  { name: 'Chow Tai Fook Inn', location: 'Mong Kok' },
  { name: 'Lily Garden Boutique Hotel', location: 'Mong Kok' },
  { name: 'Win Hotel', location: 'Mong Kok' },
  { name: 'Wai Fan Hotel', location: 'Yau Ma Tei' },
  { name: 'GreenTree Inn Hong Kong', location: 'Sham Shui Po' },
  { name: 'Largos Hotel', location: 'Sham Shui Po' },
  { name: 'Newton Place Hotel', location: 'Kwun Tong' },
  { name: 'Bay Bridge Lifestyle Retreat', location: 'Tsuen Wan' },
  { name: 'Gold Coast Hotel', location: 'Tuen Mun' },
  { name: 'Sea Cuisine Hotel', location: 'Sai Kung' },
  { name: 'Sai Kung Outdoor Recreation Centre', location: 'Sai Kung' },
  { name: 'Pak Tam Chung Hostel', location: 'Sai Kung' },
  { name: 'Cheung Chau B&B', location: 'Cheung Chau' },
  { name: 'Warwick Hotel Cheung Chau', location: 'Cheung Chau' },
  { name: 'Concerto Inn', location: 'Lamma Island' },
  { name: 'Espace Elastique', location: 'Lamma Island' },
  { name: 'Nina Hotel Tsuen Wan West', location: 'Tsuen Wan' },
  { name: 'Nina Hotel Causeway Bay', location: 'Causeway Bay' },
  { name: 'Nina Hotel Island South', location: 'Wong Chuk Hang' },
  { name: 'Nina Hotel Kowloon East', location: 'Kwun Tong' },
  { name: 'EAST Hong Kong', location: 'Tai Koo' },
  { name: 'Le Boutique Hotel', location: 'Causeway Bay' },
  { name: 'Bridal Tea House Hung Hom 2', location: 'Hung Hom' },
  { name: 'Bridal Tea House Hung Hom 3', location: 'Hung Hom' },
  { name: 'iclub AMTD Sheung Wan Hotel', location: 'Sheung Wan' },
  { name: 'iclub Classic Hotel', location: 'Wan Chai' },
  { name: 'iclub Mongkok Hotel North', location: 'Mong Kok' },
  { name: 'CityCabin Wanchai', location: 'Wan Chai' },
  { name: 'CityCabin Causeway Bay', location: 'Causeway Bay' },
  { name: 'Comfort Hotel Hong Kong', location: 'Tsim Sha Tsui' },
];
