// GENERATED BY script
// DO NOT EDIT IT MANUALLY

import * as React from 'react';
import { Pressable } from 'react-native';

import IconBase from '@/components/icons/IconBase';
import type { IconBaseProps, IconData } from '@/components/icons/types';

import data from './Notion.json';

const Notion = React.forwardRef<React.ElementRef<typeof Pressable>, IconBaseProps>(
  ({ onPress, ...props }, ref) => (
    <Pressable onPress={onPress} ref={ref}>
      <IconBase {...props} data={data as IconData} />
    </Pressable>
  )
);

Notion.displayName = 'Notion';

export default Notion;
